language: node_js
node_js:
  - 0.12
  
before_script:
  - npm install -g docpad
script: docpad generate --env static
branches:
  only:
    - master
    
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master